apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: staticserver
  name: staticserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticserver
  template:
    metadata:
      labels:
        app: staticserver
    spec:
      containers:
      - image: abzaver/journal-static-files:0.1
        imagePullPolicy: Always
        name: staticserver
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            cpu: "1.0"
            memory: "1G"
          limits:
            cpu: "1.0"
            memory: "1G"
      dnsPolicy: ClusterFirst
      restartPolicy: Always